### ISSUE TITLE
parser fix

### ISSUE THREAD

**Issue by dashed** [dat2/graphql-rust#1]
Untested proposal for https://github.com/dat2/graphql-rust/blob/4bae683e774ad7f65da6b5b187e07fc341e29df8/src/parser.rs#L183

``` rust
let parser: SimpleResult<I,Name> = parse!{i;
    let _name = name();

    let _ws_or_eol = either(
        white_space,
        line_terminator
    );

    let _colon = token(b':');

    ret _name
};
```

**Comment by dat2** [comment]
This was fixed by https://github.com/dat2/graphql-rust/commit/c179a25359310a4a700d43685c95ad6cf70f2b7c
